### ISSUE TITLE
Endpoint GET Challenges/{idChallenge}/related (Controller)

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#19]
Requisitos:

* Es necesario diseñar un objeto RelatedDTO (véanse las especificaciones). Véase **challenges.json** dentro de itachallenge-challenge.
* Es necesario añadir paginación. Utilizar para ello devolución de objetos GenericResultDTO. El objeto tipo embebido debe ser ChallengeDTO, con la info mínima necesaria de Challenge para ser mostrado en Frontend
* Parte de código utilizable en  #261  
* **Último código disponible en branch feature19f** (véase #367)

**Descomposición de tareas:**

* Modificar capa Controller + test.
* Revisión validación de parámetros (utilización de anotación @Valid)

**Comment by mmanzanomo** [comment]
Se ha realizado la revisión y pasa los test correctamente.

**Comment by AdriaMartiComas** [comment]
PR revisada, cumple con los requisitos

**Comment by jonatanvicente** [comment]
La PR solicitada es errónea. Cambia los nombres de las definiciones de un challenge añadiendo la partícula ('related_').

**Comment by jonatanvicente** [comment]
El formato del resultado debe ser exactamente como el siguiente: 

![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/1706861/13c0bc2c-3d1f-47c2-9e13-8ce43deb3f60)
