### ISSUE TITLE
Creación de endpoint GET Challenges/idChallenge + Service Layer

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#20]

**Comment by PabloMartinFluvia** [comment]
Warning: posible YAGNI. Este endpoint no será requerido por el FE para poder implementar **ninguna** de las user stories demandadas. No parece que sea necesario devolver un ChallengeDtoespecífico con toda la info (según esquema del data-challenge.json).
* Para la sección de retos no es necesario Feature#5
