### ISSUE TITLE
Creación de endpoint GET solution del usuario

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#228]
* **GET /itachallenge/api/v1/user/solution/user/{idUser}/challenge/{idChallenge}/language/{idLanguage}**
* Véase file endpoints.xlsx en https://github.com/IT-Academy-BCN/ita-challenges-backend/wiki
* Creación de Controller + Service Layer + Repository (es posible que alguna funcionalidad ya esté creada)

**Comment by DARucker** [comment]
1. El endpoint a considerar es: GET /itachallenge/api/v1/user/solution/user/{idUser}/challenge/{idChallenge}/language/{idLanguage}
2. Filtra la colección user_score.json
3. Retorna: 200 OK + solutions-user.json

**Comment by mmanzanomo** [comment]
* Se ha realizado la comprobación del *endpoint* y devuelve las soluciones a un desafío y lenguaje dado.
* Se ha utilizado el archivo de data dummy *user_score2.json* para la realización de las pruebas. Para la carga de la información a la BD se hace uso de load-data2.bat o load-data2.sh.

* Para la carga con load-data2.sh hay que especificar la BD Challenges tal y como se especifica en load-data2.bat. Se debería arreglar el script load-data2.sh: 

``` 
mongoimport --db=challenges --username admin_challenges --authenticationDatabase admin --password xxxxxxxxxxxxxxx --collection=user_score2 --jsonArray --file=user_score2.json

```
