### ISSUE TITLE
Challenge: GET Testing Params (Controller + Service Layer + Repository Layer)

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#321]
* Creación de endpoint que provea los testing params necesarios para el test de soluciones que el usuario aporta
* **URL:** /itachallenge/api/v1/challenge/test/params/{idChallenge}/language/{idLanguage}
* Creación de las 3 capas + test unitario de cada una
* No necesita paginación en el resultado
* Revisar endpoints.xlsx

**Comment by bowserchris** [comment]
Propuesta:

ChallengeDocument de momento no devuelve el testing_values de challenges.json. Analizando lo que falta propongo de hacer lo siguiente:

1. Crear TestingValueDocument - con 2 atributos de List<?> "in_param" & "out_param"
2. Crear TestingValueDto - con los 2 atributos anteriores con index value 0 y 1 respectivamente
3. Actualizar ChallengeDocument con decima campo de List<TestingValueDocument> testing_values
4. Actualizar ChallengeDto con indice de 9 para el nuevo campo
5. Crear nuevo metodo en IChallengeService Mono<GenericResultDto<TestingValueDto>>(O challengedto si queremos entero) getChallengeByIdAndLanguage(String idChallenge, String idLanguage)
6. Aplicar la logica del interfaz arriba en el ChallengeServiceImp
7. Crear controller con endpoint "/test/params/{idChallenge}/language/{idLanguage}" con 2 path variables string. Devolvera Mono<GenericResultDto<TestingValueDto>> o  challengedto

La duda que tengo es el casting del unboxing, porque hay que declarar que seria cada objeto (ya que hay strings, ints, booleans y arrays de ellos) al devolver porque son datatipos primitivos y al compilar dara error sin declarar que tipos devuelve.

enlaces a revisar: https://www.baeldung.com/java-generics (para metodos y asegurar que funciona con reactivo)

**Comment by bowserchris** [comment]
Possible casting with : https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/reflect/TypeUtils.html

**Comment by bowserchris** [comment]
Arreglado lo de los campos siendo devueltos vacios, json y field names no encajaban, por eso no funcionaba. de momento todo. queda pendiente:

- [ ] los strings con ',' se cortan en 2 cuando tienes que ser 1 string. OpenCSV library  es una posibilidad o hacer un metodo parser, [baeldung link](https://www.baeldung.com/java-split-string-commas)
- [ ] el metodo gettestingparams devuelve solo 1 dto, incluso cuando hay varios. no itera lista completa

**Comment by joseRodriguezCubero** [comment]
- Test realizados para Dto, service, document y controller.
- refactorización del resto de clases de test por la intrusión de la nueva clase TestingValueDocument y TestingValueDto. 
- Revisados endpoints.xlsx
