### ISSUE TITLE
Challenges: inclusión de LOCALE en Repository Layer

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#340]
Es necesario incluir el campo Locale, modificando Repository Layer + tests en los métodos de Repository que proveen la info, ya que se han añadido atributos en diversos campos String.
La devolución está descrita en data-challenge.out.json

**Comment by leibaral** [comment]
![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/57914114/a34a5cc3-b4bf-4216-bb38-6ad7720f5170)

**Comment by leibaral** [comment]
.
