### ISSUE TITLE
Modificación endpoint PUT /itachallenge/api/v1/user/solution/ (Controller & Service & Repository Layers)

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#384]
Es necesario alterar el funcionamiento del endpoint PUT /itachallenge/api/v1/user/solution/.

**Casuística**

Cuando un usuario envía una solución, ésta se guarda en base de datos o la altera si ya existía. 
* Al recibirla, es necesario comprobar si existe una solución para ese challenge, usuario y language. 
      * Si existe, se fija el texto de la solución y se cambia el status a STARTED.
      * Si no existe, se fija la solución con status STARTED
      * Sólo se admitirá el parámetro status de entrada con valor a ENDED (el usuario envía la solución). No se admitirá ningún otro valor en este parámetro. En caso de que el campo tenga otro valor de entrada, es necesario devolver 400-BadREquest y un json indicando el mensaje "status not allowed" en un objeto de error semejante al de otros microservicios (véase ita-challenges micro).
      * Los parámetros requeridos son: uuid_challenge, uuid_language, uuid_user
      * El campo status en base de datos sólo podrá tener los valores "EMPTY","STARTED" o "ENDED" (UPPER case).

Véase [endpoints.xlsx](https://github.com/IT-Academy-BCN/ita-challenges-backend/files/14010589/endpoints.xlsx) y [solution.user.in.txt](https://github.com/IT-Academy-BCN/ita-challenges-backend/files/14010602/solution.user.in.txt)

**Comment by Msoler92** [comment]
En estos momentos, el endpoint acepta paràmetros status de entrada diferentes a "ENDED".


![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/124594049/3b6fbc1b-964f-42f8-b81b-c487c9d31f1c)

Muevo a Doing para revisión
