### ISSUE TITLE
Bug: Error 500 en invocacion /itachallenge/api/v1/challenge/challenges/{idParam}

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#391]
**Estimacion: 5**

La invocación del endpoint indicado arroja error 500 con el parametro 5a72d6cb-3217-4d75-9368-689ed48cb9ec
Este UUID es correcto, pero al eliminar algún caracter de él, el endpoint arroja 500-InternalServerError.
La exception BadUUIDException es capturada, pero no se refleja en la salida del endpoint. Adjunto traza.

![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/1706861/1c1a1dde-7c1f-4dda-94dc-e326e3d36567)

**Comment by bowserchris** [comment]
Metodo switchIfEmpty devuelve error con mensaje y es aceptado como Mono en controller y compilador si no encuentra el documento deseado, y queremos repetirlo para baduuidexception. Intentaba mirar los siguientes metodos por si es BadUUIDException:

- onErrorMap
- onErrorResume
- onErrorReturn
- doOnError

todos saltan en la cadena del mapping y aparecen en la consola, pero no puede devolver el mensaje al controller. el metodo onErrorReturn promete pero solo acepta la clase de error (baduuidexception.class) y un default value (de mono generico con dto) como parametros, no devuelve el error en si o string de mensaje. 
revisando reestructar el metodo getChallengeById con try catch o if else.

**Comment by bowserchris** [comment]
incluso dividiendo y repetiendo codigo para que arroja el error a la manera que lo hace el .switchIfEmpty(Mono.error(ChallengeNotFoundException), dentro de un if else y ademas dentro de un try catch, aun asi el error no esta deveulto y solo aparece en la consola. 
Sigue arrojada correctamente pero no lo recibe el controller. 
Investigando mas de otras maneras para excepciones.
