### ISSUE TITLE
Centralización de Swagger Documents

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#392]
**Rama Feature#392**

Es necesario crear un sólo punto de entrada para todos los **Documentos Swagger** del proyecto:
* Actualmente todos los microservicios tienen Swagger habilitado en su propia URL. No obstante, se desea **acceder a un único punto de entrada que aúne todos los documentos de todos los endpoints disponibles.** Este punto de entrada será posteriormente redireccionado por la API Gateway general del proyecto.
* Para ello, se ha creado el **microservicio itachallenge-document**. Éste recibirá la delegación de todos los Swagger de los demás microservicios.
* Como prueba, **se ha añadido en la configuración de itachallenge-challenge en bootstrap.yml l**a delegación de rutas Swagger del micro Challege al nuevo microservicio.
* **Será necesario:**
   - Probar la delegación de Swagger del micro Challenge al micro Document
   - Crear el/los endpoints necesarios en el micro Document para que reciba las redirecciones y aúne la Documentación en un solo endpoint.
   - Hacer extensible el procedimiento a todos los demás microservicios.

**Comment by plopezgit** [comment]
08/04/2024 Actions en al menos 2 maquinas distintas:

- [x] diff review entre develop estable y rama "Feature#392" con especial atención a _config files_:

- **No se encontraron diferencias** relevantes en archivos de configuración o clases que pudieran crear problemas en build
- **Se encontro un caso de test negativo configurado para esperar un resultado positivo**.  Por tanto se ajusto lo siguiente:

- [x] refactor en UserControllerTest class > getChallengeUserPercentageTest()

- [x] test automáticos de Challenges 100% exitosos

- [x] build de la rama exitoso, si 106 test pasan

- [x] inicialización correcta de todos los micro servicios.

- [x] navegación en la documentación centra via http://localhost:8769/swagger-ui exitosa

**Next:** comentar este procedimiento en próxima daily, invertir tiempo adicional en detectar posibles mejoras en el código y clean code, y proponer un proximo pull request.

- **Nota:** existe una rama llamada "feature#392" en minúsculas que no esta actualizada y presenta cambios importantes en ciertos archivos del folder **.github/workflows**/ env.CL.dev (nuevo), test_invoke_ssh.dev.yml, test_upload_image.dev.yml. **Dado que no es la rama en foco, descartamos importancia de este hecho.**

CC:
@Msoler92 
@Lsans80 
@jonatanvicente

**Comment by plopezgit** [comment]
PR actualizada basado en las acciones acordadas!
CC: @jonatanvicente @Msoler92
