### ISSUE TITLE
Revisión del filtrado /GET Challenges?idLanguage=99&level=EASY + paginación del resultado

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#397]
* Es necesario revisar el filtrado por parámetros. El filtrado no funciona bien.

* La paginación ya está implementada en otro endpoint utilizando Spring Framework en el método ChallengeServiceImp.getAllChallenges y es utilizada por el endpoint GET /itachallenge/api/v1/challenge/challenges utilizando correctamente los parámetros offset y limit.

**Comment by ArnauBurguera** [comment]
El filtrado no funciona bien. Una invocación simple con filtrado /itachallenge/api/v1/challenge/challenges?idLanguage=660e1b18-0c0a-4262-a28a-85de9df6ac5m (idLanguage incorrecto) arroja la totalidad de los elementos challenges de la collection de DB.
Es necesario revisar el filtrado. Adjunto screenshot
[Pasted.image.png](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/1706861/cdee8c6e-82c6-4c0f-9f5d-ff8b1ab17eb4)
