### ISSUE TITLE
Wrong Output Message: Challenge not found

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#430]
Cuando se invoca /itachallenge/api/v1/challenge/challenges/{idChallenge} pero el idChallenge no existe, se devuelve un HTTPStatus 200 correctamente. Sin embargo, el mensaje de salida es como se muestra en la imagen 1. 

* Debe ser un mensaje JSON, de la misma manera como cuando se pasa un UUID incorrecto.

![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/1706861/8ed08d4f-c89f-492b-b6ea-51b0c0966530)
![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/1706861/cbc3a9d2-74e4-4d71-8d08-44a9cc1a83eb)

**Comment by plopezgit** [comment]
Test manual evidencia:

Requerimiento: json con mensaje de respuesta cuando idChallenge no existe

![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/131781567/8e3cf69e-e621-46f0-b737-0638a5b34e9e)

--

json con mensaje de respuesta cuando idChallenge no es correcto

![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/131781567/d142010d-d1d2-4f4a-b651-4e31590dbff5)

json con información de challenge dado un idChallenge existente:

![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/131781567/982363e6-c92e-4de3-b48c-003ec62a338c)

**Comment by plopezgit** [comment]
Manual test evidence on 11/04/2024:

Requerimiento: json con mensaje de respuesta cuando idChallenge no existe

![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/131781567/4e47554b-80ff-43d4-9d87-23a3d9733471)

- 
json con mensaje de respuesta cuando idChallenge no es correcto

![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/131781567/49a9726f-e0c1-41a1-a723-040b61d913a5)

-
json con información de challenge dado un idChallenge existente:

![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/131781567/56f0ea1b-0704-4b32-95e8-5686bbb4dbfc)


Swagger UI  response code update for documentation:

![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/131781567/2c95d3eb-3ff4-4cc8-b262-3b9b092a1fae)
