### ISSUE TITLE
Enhancement: endpoint /version (todos los micros)

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#474]
Es necesario revisar algunos detalles en la implementación de los endpoints /version:
* El micro Document no tiene accesible este endpoint (es el punto de acceso de Swagger para todos los demás). INvocando el endpoint /version desde http:///swagger-ui/index.html arroja error 500
* En todos los microservicios, hay que asegurarse de que el test de controlador del endpoint /version lo ejecuta contra la versión del fichero de configuración de test (usualmente application.yml de test). Si no hay un file application.yml de test, es necesario crearlo y verificar que la fase test pasa en todos los casos. De no ser así, habría que cambiar el test de /version en Controller cada vez que se suba la versión.

**Comment by joseRodriguezCubero** [comment]
En itachallenge-document controller.

He testeado de todas formas posibles, porque no funciona en reactivo este método:
```@GetMapping("/version")
    public Mono<ResponseEntity<Map<String, String>>> getVersion() {
        Map<String, String> response = new HashMap<>();
        response.put("application_name", appName);
        response.put("version", version);
        return Mono.just(ResponseEntity.ok(response));
    }
```
Solo funciona en no-reactivo:
```@GetMapping("/version")
public ResponseEntity<Map<String, String>> getVersion() {
    Map<String, String> response = new HashMap<>();
    response.put("application_name", appName);
    response.put("version", version);
    return ResponseEntity.ok(response);
}
```
El problema al parecer empezó cuando se implemento el **getSelectetOpenApi**. No es reactivo y hace uso de **Feign** para hacer llamadas a otros micros que por lo visto son bloqueantes. No digo que sea la causa porque en realidad no la he encontrado. Copilot sugiere que el uso de diferentes tecnologías reactivas y no reactivas puede causar conflictos. De momento dejo el método en no-reactivo para que funcione. Reescribir getSelectedOpenApi a reactivo comportaría mucha refactorización y  además posiblemente no sea la causa final del problema.

Añadido application.yml para test de documents.
