### ISSUE TITLE
Testing Consul + micros

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#56]

**Comment by PabloMartinFluvia** [comment]
Prioridad: ?

**Comment by Pedro-Tejero-Diez** [comment]
Hola, no controlo mucho pero me he añadido a esta tarea porque ponía "help wanted" así que a partir de aquí debería ponerla en "doing" no es así? me espero a que me digais

**Comment by Pedro-Tejero-Diez** [comment]
> Hola, no controlo mucho pero me he añadido a esta tarea porque ponía "help wanted" así que a partir de aquí debería ponerla en "doing" no es así? me espero a que me digais
