### ISSUE TITLE
Sandbox Phase 2A - Creation a Sandbox using Docker container

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#568]
We need to create a Docker image that contains all elements necessary to compile and execute Java Code. 

**PHASE 1 Character Filters:**

1. Create a class to escape Java characters from the frontend.
2. Create a class to assign valid ASCII characters and link them to collections
- Evaluate the performance of hashmaps, linkedtrees, arrays, maps, etc.
- Avoid using the keyword synchronize.
More information:
Thinking in Java - Bruce Eckel 4h Edition

/////////////////Edit Dani Diaz /////////////////

Branch feature#568h

**Description:** 
In the **feature#568h** branch, the user can write all the code in a public Main template, etc. It can only check that the code compiles, runs, and produces output. It does not support BlackBoxTest.

In the **feature#568v3** branch, the user is required to create it with established variables that will be the args[]. This way, a BlackBoxTest can be performed where, through Parameterized Test, those variables can be changed to verify if the code actually works and meets the requirements. In this branch, tests are being created exactly as they are in challenges.json (within the micro-challenge).

**Branch feature#568h**
- Implemented a Chain of Responsibility with the following filters:

- UnescapeJava: Replaces escaped characters that the Frontend must use to send the code to the Backend.
- ASCIIFilter: Verifies that the code contains only valid ASCII characters (0-127).   -> Used a Bitset to better performance.
- HTMLSanitizer: Sanitizes the code to prevent possible HTML injection attacks.
- KeywordFilter: Checks that the code does not contain reserved keywords that could pose a risk during execution. -> Prohibited words how import, etc.
- SecurityFilter: Ensures that the code does not use libraries or modules that could be dangerous for execution. -> Prohibited libraries and modules.

- Created the DockerExecutor class
The DockerExecutor is responsible for launching a Docker container with a Java image to execute the user's code. It includes a method to terminate the container in case of issues such as infinite loops, and implements AutoCloseable to ensure proper resource management.

- Created the CodeProcessingManager class
The CodeProcessingManager manages the entire flow of processing user code. It first applies the chain of filters to validate the code, and if the filters pass, it invokes DockerExecutor to execute the code within a container. After execution, it performs the following steps to calculate the score:

Compilation Check: Verifies if the code compiled successfully.
Execution Check: Verifies if the code executed without errors.
Result Comparison: Compares the execution result with the expected output. The scoring logic handles different levels of accuracy:

Exact match with the expected result.
Partial match (i.e., the result contains the expected output).
No match (i.e., the result does not contain the expected output).
Don't compile the code.
Code compile but no execute.
Finally, it generates a ScoreResponse based on these checks and returns it to the controller.

** Added a postman collection with new body to test.
** Added aditional endpoint in postman with body with infinite loop to try. 

** Added a MD in Spanish and English to explain the Sandbox and methods. 

**Branch feature#568v3**

Same about 568h but with this modifies. 

DockerExecutor has been modified to now accept a new parameter, which is the args[], to try IN values and OUT values to try BlackBox.
Changes have been made to DockerExecutorTest to implement all the tests from the website.(Only Java Exercises) 
Need fix the enunciates exercises. All exercises need same inputs and outputs. 
Changes have been made to CodeProcessingManager to now wait to receive the inputs and outputs of the testing values via ZMQ. (in development)

**Comment by danidiazd** [comment]
Description
- Implemented a Chain of Responsibility with the following filters:

UnescapeJava: Replaces escaped characters that the Frontend must use to send the code to the Backend.
ASCIIFilter: Verifies that the code contains only valid ASCII characters (0-127).   -> Used a Bitset to better performance.
HTMLSanitizer: Sanitizes the code to prevent possible HTML injection attacks.
KeywordFilter: Checks that the code does not contain reserved keywords that could pose a risk during execution. -> Prohibited words how import, etc.
SecurityFilter: Ensures that the code does not use libraries or modules that could be dangerous for execution. -> Prohibited libraries and modules.
- Created the DockerExecutor class
The DockerExecutor is responsible for launching a Docker container with a Java image to execute the user's code. It includes a method to terminate the container in case of issues such as infinite loops, and implements AutoCloseable to ensure proper resource management.

- Created the CodeProcessingManager class
The CodeProcessingManager manages the entire flow of processing user code. It first applies the chain of filters to validate the code, and if the filters pass, it invokes DockerExecutor to execute the code within a container. After execution, it performs the following steps to calculate the score:

Compilation Check: Verifies if the code compiled successfully.
Execution Check: Verifies if the code executed without errors.
Result Comparison: Compares the execution result with the expected output. The scoring logic handles different levels of accuracy:

Exact match with the expected result.
Partial match (i.e., the result contains the expected output).
No match (i.e., the result does not contain the expected output).
Don't compile the code.
Code compile but no execute.
Finally, it generates a ScoreResponse based on these checks and returns it to the controller.
