### ISSUE TITLE
Solutions Repository + Dummies Data

### ISSUE THREAD

**Issue by PabloMartinFluvia** [IT-Academy-BCN/ita-challenges-backend#89]
**Estimacion: 2**

Es necesario tener presente lo siguiente:
* **MongoDB NO admite UUID como identifier** (utiliza ObjectId).
* UUID es mapeado por el driver a java.util. UUID, mientras que ObjectId es mapeado a org.bson.types.ObjectId.
* Es necesario configurar Spring para forzar la inserción de un campo UUID.
* Véase https://www.baeldung.com/java-mongodb-uuid, y construir el **punto 6 personalizando nuestros repositorios y sobreescribiendo los métodos que usan UUID**.
* **Al probar, ejecutar una inserción con campos UUID para ver cómo lo toma Mongo sobre una base de datos estática** (no Docker). Después, tunear el test para su ejecución correcta con TestContainer, haciendo coincidir los tipos de inserciones por script con los tipos Java.
* Muy probablemente habrá que prescindir de las clases dentro del package ''converter''.
* **Configuración correcta de acceso a Mongo en micro Challenge - application.yml**

**Comment by jonatanvicente** [comment]
* Es necesario cambiar la definición de user_score.json para permitir guardado de varias solutions por usuario (limitado en otra capa)
* Es necesario inyectar en capa RepositoryTest el script de carga de datos dummy, exactamente igual a como se hace en develop (file user_score.json)
* Es necesario alinear objetos Document con los cambios introducidos en el modelo de datos Mongo
